add functionality to counter
isdi-coders-202207-bcn-coding-adventure/berta-floran-front pull request #4
Opened 2022-08-23 13:21 UTC by bertarosalia

2022-08-24 11:14 UTC, mariogl requested changes

2022-08-24 11:14 UTC, mariogl commented on src/components/Counter/Counter.tsx
> +  const initialTime: ICountDown = {
La fecha tiene que estar guardada como Date, y tiene que estar en algún lugar a disposición de toda la app.

2022-08-24 16:37 UTC, rtrepis commented on src/components/Counter/Counter.tsx
> +const getTimeRemaining = (dateline: Date) => {
Podríamos refactorizar esta función he importarla. En una carpeta utitys

2022-08-24 16:37 UTC, rtrepis commented on src/components/Counter/Counter.tsx
>  const Counter = (): JSX.Element => {
Podriamos quitarle responsabilidades ha este componente

2022-08-24 16:55 UTC, bertarosalia commented on src/components/Counter/Counter.tsx
> +const getTimeRemaining = (dateline: Date) => {
vale, lo tendré en cuenta

2022-08-24 16:57 UTC, bertarosalia commented on src/components/Counter/Counter.tsx
>  const Counter = (): JSX.Element => {
pensaba que estaría mejor ahí, pero lo pondré en otro documento

2022-08-24 17:37 UTC, mariogl submitted a review, later dismissed
Fase 5. Testea el componente contador.

2022-08-24 18:44 UTC, mariogl requested changes
He levantado la app y el contador no se mueve.

Aparte, debería estar centrado en vertical y horizontal respecto al viewport.

2022-08-24 20:41 UTC, bertarosalia commented
> Fase 5. Testea el componente contador.



> He levantado la app y el contador no se mueve.
> 
> Aparte, debería estar centrado en vertical y horizontal respecto al viewport.



> He levantado la app y el contador no se mueve.
> 
> Aparte, debería estar centrado en vertical y horizontal respecto al viewport.

Mario, el contador sí se mueve, y va bien...no sé cuál será el problema por el que no lo ves.
En cuanto a centrarlo, estoy en ello

2022-08-25 10:28 UTC, mariogl approved these changes
Fase 6. Crea dos rutas: /home y /register. En /home debe verse el contador si aún no ha llegado la fecha clave, y si ya ha pasado debe verse un encabezado.

2022-08-25 10:32 UTC, bertarosalia commented
> Fase 6. Crea dos rutas: /home y /register. En /home debe verse el contador si aún no ha llegado la fecha clave, y si ya ha pasado debe verse un encabezado.

Mario, aun no he hecho el test. He hecho los cambios para que el contador se vea en el centro de la pantalla, y ahora subiré los cambios en los que muevo de documento la función que me dijeron en la code review. 
subiré los cambios ahora, y me pongo con el test

2022-08-25 10:32 UTC, merged